version: '3.9'

services:
  chatbot:
    build: ./chatbot_app
    ports:
      - "5000:5000"
    environment:
      - SLACK_APP_TOKEN
      - SLACK_BOT_TOKEN
    links:
      - db

  db:
    build: ./database
    ports:
      - "27018:27017"